extends Node2D
## Run orchestrator: owns run state (time, kills, xp) and wires everything.
## Children signal up; Main calls down. Nothing else knows about Main.

const ARENA: Rect2 = Rect2(0, 0, 1280, 720)

const XP_GEM_SCENE: PackedScene = preload("res://scenes/pickups/xp_gem.tscn")
const DEATH_BURST_SCENE: PackedScene = preload("res://scenes/fx/death_burst.tscn")
const HEALTH_PICKUP_SCENE: PackedScene = preload("res://scenes/pickups/health_pickup.tscn")
const POWER_UP_SCENE: PackedScene = preload("res://scenes/pickups/power_up.tscn")

## Power-ups are the SHORT-TERM counterpart to upgrades: an upgrade changes the
## rest of the run, a power-up changes the next few seconds. Rare on purpose —
## the moment has to feel like luck, not income.
const POWER_UPS: Array[PowerUpResource] = [
	preload("res://resources/powerups/shield.tres"),
	preload("res://resources/powerups/power.tres"),
	preload("res://resources/powerups/haste.tres"),
	preload("res://resources/powerups/collect.tres"),
]
## Playtest 2026-08-02: at 1.8% a tester played to level 9 without seeing one.
## Rare should mean 'a moment', not 'a rumour'.
const POWER_UP_DROP_CHANCE: float = 0.040

## Health is a world drop, not a level-up option. Only drops when the player
## is actually hurt, so it can never be the wasted pick a heal-at-full-HP was.
const HEALTH_DROP_CHANCE: float = 0.045

## Explicit preloads, not DirAccess scanning — directory listings misbehave
## inside exported .pck files (resources get .remap suffixes).
## GENERATED by tools/gen_upgrades.gd's companion step — do not hand-edit;
## with 36 entries, a hand-maintained list is how one silently goes missing.
const UPGRADE_LIST: Array[UpgradeResource] = [
	preload("res://resources/upgrades/aegis.tres"),
	preload("res://resources/upgrades/bandage.tres"),
	preload("res://resources/upgrades/barrage.tres"),
	preload("res://resources/upgrades/cadence.tres"),
	preload("res://resources/upgrades/cannonball.tres"),
	preload("res://resources/upgrades/carapace.tres"),
	preload("res://resources/upgrades/chain_lightning.tres"),
	preload("res://resources/upgrades/cryo_rounds.tres"),
	preload("res://resources/upgrades/event_horizon.tres"),
	preload("res://resources/upgrades/executioner.tres"),
	preload("res://resources/upgrades/focus.tres"),
	preload("res://resources/upgrades/fusillade.tres"),
	preload("res://resources/upgrades/greed.tres"),
	preload("res://resources/upgrades/honed_edge.tres"),
	preload("res://resources/upgrades/lodestone.tres"),
	preload("res://resources/upgrades/magnetism.tres"),
	preload("res://resources/upgrades/momentum.tres"),
	preload("res://resources/upgrades/nova_orbit.tres"),
	preload("res://resources/upgrades/orbit_count.tres"),
	preload("res://resources/upgrades/orbit_radius.tres"),
	preload("res://resources/upgrades/orbit_speed.tres"),
	preload("res://resources/upgrades/overclock.tres"),
	preload("res://resources/upgrades/overdrive.tres"),
	preload("res://resources/upgrades/pierce.tres"),
	preload("res://resources/upgrades/prism_core.tres"),
	preload("res://resources/upgrades/rapid_fire.tres"),
	preload("res://resources/upgrades/relentless.tres"),
	preload("res://resources/upgrades/reservoir.tres"),
	preload("res://resources/upgrades/ricochet.tres"),
	preload("res://resources/upgrades/scatter.tres"),
	preload("res://resources/upgrades/scholar.tres"),
	preload("res://resources/upgrades/second_wind.tres"),
	preload("res://resources/upgrades/sharp_shots.tres"),
	preload("res://resources/upgrades/siphon.tres"),
	preload("res://resources/upgrades/split_shot.tres"),
	preload("res://resources/upgrades/swift_boots.tres"),
	preload("res://resources/upgrades/tough_hide.tres"),
	preload("res://resources/upgrades/velocity.tres"),
]

var time_survived: float = 0.0
var kills: int = 0
var total_xp: int = 0
var level: int = 1
var xp_into_level: int = 0
## id -> times taken; the pool uses this to respect stack caps.
var stacks: Dictionary = {}

var pool: UpgradePool
var run_rng: RandomNumberGenerator = RandomNumberGenerator.new()
## This run's identity. One seed drives upgrade draws, enemy choice and
## spawn placement, so replaying it reproduces the run.
var run_state: RunState
## True once victory has banked this run, so a later death in endless
## improves records without counting a second run.
var _banked: bool = false
## Level-ups since the last Rare-or-better. A cold streak that lasts a whole
## run is invisible in aggregate stats, so it gets a hard floor.
var _pity: int = 0

## Dev flags, read from user args after a bare `--` (same convention as
## ai_screenshot.gd). Inert in a normal run and in exported builds.
var _dev_stats: bool = false
var _dev_autopick: bool = false
var _dev_autocontinue: bool = false
var _dev_stats_t: float = 0.0
var _tele_t: float = 0.0

@onready var player: Player = $Player
@onready var spawner: Spawner = $Spawner
@onready var director: RunDirector = $RunDirector
@onready var bosses: Node2D = $Bosses
@onready var enemy_bolts: Node2D = $EnemyBolts
@onready var victory_screen: VictoryScreen = $Victory
@onready var enemies: Node2D = $Enemies
@onready var pickups: Node2D = $Pickups
@onready var projectiles: Node2D = $Projectiles
@onready var level_up_panel: LevelUpPanel = $LevelUpPanel
@onready var hud: Hud = $Hud
@onready var game_over: GameOverScreen = $GameOver
@onready var pause_panel: PausePanel = $PausePanel


func _ready() -> void:
	run_state = RunState.with_seed(RunState.random_seed_value())
	run_rng.seed = run_state.seed_value
	Telemetry.begin_run(run_state.seed_value)
	pool = UpgradePool.new(UPGRADE_LIST, run_rng)
	spawner.target = player
	spawner.container = enemies
	spawner.arena = ARENA
	spawner.rng = run_rng
	spawner.bolt_container = enemy_bolts
	spawner.enemy_spawned.connect(_on_enemy_spawned)
	# One RNG drives upgrades, spawn choice and spawn placement, so a seeded run
	# reproduces whole — the groundwork M3 needs for seeded runs.
	director.spawner = spawner
	director.target = player
	director.boss_container = bosses
	director.bolt_container = enemy_bolts
	director.rng = run_rng
	director.boss_spawned.connect(_on_boss_spawned)
	director.victory.connect(_on_victory)
	# The music is a CONSUMER of run intensity, not a system of its own.
	director.intensity_changed.connect(Music.set_intensity)
	player.died.connect(_on_player_died)
	player.second_wind.connect(_on_second_wind)
	player.health_changed.connect(hud.set_health)
	player.weapon.container = projectiles
	player.weapon.rng = run_rng
	player.scattergun.container = projectiles
	player.scattergun.rng = run_rng
	player.lance.rng = run_rng
	player.apply_unlocks(Meta.state.unlocks)
	level_up_panel.upgrade_chosen.connect(_on_upgrade_chosen)
	# Continuing into endless brings the layers back where they were.
	victory_screen.continued.connect(Music.resume_gameplay)
	# Auto-pause when the window loses focus. Standard QOL, and it matters
	# more here than usual: an unattended run keeps spawning and dies.
	get_window().focus_exited.connect(_pause_if_playing)
	hud.set_health(player.health.hp, player.health.max_hp)
	hud.set_xp(xp_into_level, Progression.xp_required(level), level)
	Music.play_gameplay()
	_apply_dev_flags()
	print("PRISM boot OK — Godot %s" % Engine.get_version_info()["string"])


## --dev-godmode  player takes no damage
## --dev-stats    print entity counts every 30s of game time
## --dev-autopick auto-take the first upgrade offer (a paused panel would stall
##                a headless soak run forever)
## --dev-unlocks  every weapon active regardless of the save — the only way to
##                exercise (or playtest) a gated weapon without earning it first
func _apply_dev_flags() -> void:
	for arg: String in OS.get_cmdline_user_args():
		match arg:
			"--dev-godmode":
				player.health.invincible = true
				print("[dev] godmode")
			"--dev-unlocks":
				player.apply_unlocks([MetaState.UNLOCK_ORBITAL,
						MetaState.UNLOCK_ELITE_HUNTER, MetaState.UNLOCK_ENDLESS_PROVEN])
				print("[dev] all unlocks")
			"--dev-stats":
				_dev_stats = true
				print("[dev] stats")
			"--dev-autopick":
				_dev_autopick = true
				print("[dev] autopick")
			"--dev-autocontinue":
				_dev_autocontinue = true
				print("[dev] autocontinue")
	if _dev_stats:
		print("[meta] dir=%s runs=%d wins=%d best_time=%.0f best_kills=%d unlocks=%s"
				% [OS.get_user_data_dir(), Meta.state.runs_played, Meta.state.victories,
				Meta.state.best_time, Meta.state.best_kills, str(Meta.state.unlocks)])


## Input lives in _unhandled_input, not _physics_process, because a paused tree
## runs no physics — pause would be unable to un-pause itself.
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed(&"mute"):
		get_viewport().set_input_as_handled()
		Audio.set_muted(not Audio.muted)
		if pause_panel.visible:
			pause_panel._refresh_mute()
		return
	if event.is_action_pressed(&"restart") and not _modal_open():
		get_viewport().set_input_as_handled()
		get_tree().paused = false
		get_tree().reload_current_scene()
		return
	if not event.is_action_pressed(&"pause"):
		return
	# Never steal the key from a screen that already owns the pause state.
	if _modal_open():
		return
	get_viewport().set_input_as_handled()
	if pause_panel.visible:
		pause_panel.resume()
	else:
		_pause_if_playing()


## True while another screen owns the pause. Level-up, victory and game-over all
## pause the tree themselves, and two owners of one flag is a stuck game.
func _modal_open() -> bool:
	return level_up_panel.visible or victory_screen.visible or game_over.visible


func _pause_if_playing() -> void:
	if _modal_open() or pause_panel.visible or get_tree().paused:
		return
	get_tree().paused = true
	pause_panel.show_build(UPGRADE_LIST, stacks, level, time_survived, kills)


func _physics_process(delta: float) -> void:
	# The director owns run time; Main mirrors it so there is exactly one clock.
	time_survived = director.elapsed
	run_state.elapsed = time_survived
	run_state.kills = kills
	run_state.level = level
	Telemetry.set_run_time(time_survived)
	_sample_telemetry(delta)
	hud.set_run(time_survived, kills)
	_push_buffs()
	if _dev_stats:
		_dev_stats_t += delta
		if _dev_stats_t >= 30.0:
			_dev_stats_t = 0.0
			print("[stats] t=%4.0fs enemies=%3d pickups=%3d proj=%2d bolts=%3d kills=%4d lvl=%2d bosses=%d"
					% [time_survived, enemies.get_child_count(), pickups.get_child_count(),
					projectiles.get_child_count(), enemy_bolts.get_child_count(),
					kills, level, director.bosses_alive])


func _push_buffs() -> void:
	var entries: Array = []
	for id: StringName in player.buffs.active_ids():
		entries.append({"name": String(id).to_upper(), "left": player.buffs.remaining(id)})
	hud.set_buffs(entries)


## Every 5s: the pressure curve. Answers "is the start too easy" with numbers —
## HP fraction and living-enemy count over time, not a recollection.
func _sample_telemetry(delta: float) -> void:
	if not Telemetry.enabled:
		return
	_tele_t += delta
	if _tele_t < 5.0:
		return
	_tele_t = 0.0
	Telemetry.event(&"tick", {
		"hp": player.health.hp,
		"max_hp": player.health.max_hp,
		"kills": kills,
		"lvl": level,
		"alive": enemies.get_child_count(),
		"bosses": director.bosses_alive,
	})


func _on_enemy_spawned(enemy: Enemy) -> void:
	enemy.died.connect(_on_enemy_died)


## A boss is just a very large enemy as far as kills, XP and juice are concerned
## — except in the mix, where its arrival and death are the run's loudest beats.
func _on_boss_spawned(boss: Node2D) -> void:
	boss.died.connect(_on_enemy_died)
	boss.died.connect(func(_xp: int, _at: Vector2, _tint: Color) -> void:
		Sfx.play(&"boss_death", -2.0))
	Sfx.play(&"boss_spawn", -2.0)
	player.camera.add_trauma(0.6)
	Telemetry.event(&"boss_spawn", {"alive": director.bosses_alive})
	if _dev_stats:
		print("[boss] spawned t=%.0fs alive=%d" % [time_survived, director.bosses_alive])


## Fired once, on the first boss event cleared. The reward is already banked by
## the time this runs — Continue is pure upside.
func _on_victory(_event_index: int) -> void:
	if _dev_stats:
		print("[victory] t=%.0fs kills=%d lvl=%d" % [time_survived, kills, level])
	# The victory screen waits on a button, which would stall a headless soak at
	# the exact moment endless begins — the part that most needs soaking.
	Telemetry.event(&"victory", {"kills": kills, "lvl": level})
	Music.play_victory()
	run_state.won = true
	_banked = true
	Meta.absorb_run(run_state.to_result())  # banked BEFORE the choice is offered
	if _dev_autocontinue:
		return
	get_tree().paused = true
	victory_screen.show_results(time_survived, kills, level)


func _on_enemy_died(xp_value: int, at: Vector2, tint: Color) -> void:
	kills += 1
	Telemetry.event(&"kill", {"n": kills})
	if player.stats.lifesteal_chance > 0.0 and run_rng.randf() < player.stats.lifesteal_chance:
		player.health.heal(1)
	if player.stats.implode_radius > 0.0:
		_implode(at)
	if player.health.hp < player.health.max_hp and run_rng.randf() < HEALTH_DROP_CHANCE:
		_spawn_health.call_deferred(at)
	elif run_rng.randf() < POWER_UP_DROP_CHANCE:
		_spawn_power_up.call_deferred(at)
	Sfx.play(&"pop", -6.0)
	player.camera.add_trauma(0.12)
	# died fires from a physics callback (projectile body_entered) — adding
	# physics nodes to the tree mid-flush is forbidden, so defer the spawns.
	_spawn_gem.call_deferred(xp_value, at)
	_spawn_burst.call_deferred(at, tint)


## Event Horizon: a kill drags its neighbours inward and hurts them. The pull is
## what sells it — damage alone would just be a smaller Nova.
func _implode(at: Vector2) -> void:
	var radius: float = player.stats.implode_radius
	for node: Node in get_tree().get_nodes_in_group(&"enemies"):
		var enemy: Enemy = node as Enemy
		if enemy == null:
			continue
		var offset: Vector2 = at - enemy.global_position
		var dist: float = offset.length()
		if dist > radius or dist < 0.01:
			continue
		enemy.global_position += offset.normalized() * minf(dist * 0.45, 26.0)
		enemy.take_hit(maxi(1, player.stats.damage_bonus + 1))


## Second Wind: the run does not end, and everything nearby pays for it.
func _on_second_wind(at: Vector2) -> void:
	Telemetry.event(&"second_wind", {})
	for node: Node in get_tree().get_nodes_in_group(&"enemies"):
		var enemy: Enemy = node as Enemy
		if enemy != null and at.distance_to(enemy.global_position) <= 260.0:
			enemy.take_hit(9999)


func _spawn_gem(xp_value: int, at: Vector2) -> void:
	var gem: XpGem = XP_GEM_SCENE.instantiate()
	gem.setup(xp_value, player)
	gem.position = at
	pickups.add_child(gem)
	gem.collected.connect(_on_gem_collected)
	if player.stats.greed:
		gem.attract(player)  # Greed: no gem is ever left behind


func _spawn_health(at: Vector2) -> void:
	var pickup: HealthPickup = HEALTH_PICKUP_SCENE.instantiate()
	pickup.setup(player)
	pickup.position = at
	pickups.add_child(pickup)
	pickup.collected.connect(func() -> void:
		player.health.heal(2)
		Sfx.play(&"health", -4.0))


func _spawn_power_up(at: Vector2) -> void:
	var choice: PowerUpResource = _pick_power_up()
	if choice == null:
		return
	# Logged on DROP as well as on collect: the ratio of the two answers "are
	# power-ups actually reachable, or are they dying on the floor?", which
	# collection events alone cannot tell you.
	Telemetry.event(&"powerup_drop", {"id": String(choice.id)})
	var pickup: PowerUp = POWER_UP_SCENE.instantiate()
	pickup.setup(choice, player)
	pickup.position = at
	pickups.add_child(pickup)
	pickup.collected.connect(_on_power_up_collected)


func _pick_power_up() -> PowerUpResource:
	var total: float = 0.0
	for p: PowerUpResource in POWER_UPS:
		total += maxf(0.0, p.weight)
	if total <= 0.0:
		return null
	var roll: float = run_rng.randf() * total
	for p: PowerUpResource in POWER_UPS:
		roll -= maxf(0.0, p.weight)
		if roll <= 0.0:
			return p
	return POWER_UPS[POWER_UPS.size() - 1]


func _on_power_up_collected(resource: PowerUpResource) -> void:
	Sfx.play(&"powerup", -4.0)
	player.camera.add_trauma(0.15)
	Telemetry.event(&"powerup_take", {"id": String(resource.id)})
	if resource.is_instant():
		_collect_all_gems()
		return
	player.buffs.grant(resource.buff_id(), resource.duration)


## The Collect power-up: every gem on the map homes in at once. Instant rather
## than timed because a "magnet for 8s" would just be a worse Magnetism upgrade.
func _collect_all_gems() -> void:
	for child: Node in pickups.get_children():
		if child is XpGem:
			(child as XpGem).attract(player)


func _spawn_burst(at: Vector2, tint: Color) -> void:
	var burst: CPUParticles2D = DEATH_BURST_SCENE.instantiate()
	burst.setup(tint)
	burst.position = at
	pickups.add_child(burst)


func _on_gem_collected(xp_value: int) -> void:
	Sfx.play(&"pickup", -8.0)
	var gained: int = Progression.xp_gain(xp_value, player.stats.xp_mult)
	total_xp += gained
	xp_into_level += gained
	_check_level_up()


## Drains banked XP one level at a time. Loops rather than recursing so a single
## fat gem worth several levels resolves cleanly: we break to show each offer,
## and _on_upgrade_chosen re-enters to continue draining. Every exit path
## refreshes the HUD — the old version didn't, so chained level-ups left the XP
## bar stale until the next gem.
func _check_level_up() -> void:
	while xp_into_level >= Progression.xp_required(level):
		xp_into_level -= Progression.xp_required(level)
		level += 1
		var offers: Array[UpgradeResource] = pool.draw_tiered(
				3, stacks, Meta.state.unlocks,
				Rarity.progress_for_level(level), _pity)
		_pity = 0 if pool.rolled_high else _pity + 1
		if offers.is_empty():
			continue  # everything maxed — bank the level, keep playing
		# Log what was OFFERED, not just what was taken: a pick rate without a
		# denominator says "common upgrades are popular", which is worthless.
		var offered_ids: Array[String] = []
		var offered_tiers: Array[int] = []
		for u: UpgradeResource in offers:
			offered_ids.append(String(u.id))
			offered_tiers.append(int(u.rarity))
		Telemetry.event(&"offer", {"lvl": level, "ids": offered_ids, "tiers": offered_tiers})
		if _dev_autopick:
			_on_upgrade_chosen.call_deferred(offers[0])
			break
		Sfx.play(&"levelup")
		get_tree().paused = true
		level_up_panel.show_offers(offers, level)
		break
	hud.set_xp(xp_into_level, Progression.xp_required(level), level)


func _on_upgrade_chosen(upgrade: UpgradeResource) -> void:
	Telemetry.event(&"pick", {"lvl": level, "id": String(upgrade.id),
			"tier": int(upgrade.rarity),
			"stack": int(stacks.get(upgrade.id, 0)) + 1})
	stacks[upgrade.id] = int(stacks.get(upgrade.id, 0)) + 1
	upgrade.apply_to(player.stats)
	# Two effects touch live Health, which Stats can't know about:
	match upgrade.effect:
		UpgradeResource.Effect.MAX_HP:
			player.health.raise_max(int(upgrade.magnitude))
		UpgradeResource.Effect.HEAL:
			player.health.heal(int(upgrade.magnitude))
	player.refresh_from_stats()
	get_tree().paused = false
	_check_level_up()  # banked XP can trigger another level immediately


func _on_player_died() -> void:
	Telemetry.event(&"death", {"kills": kills, "lvl": level})
	Telemetry.end_run("death", {"kills": kills, "lvl": level, "won": run_state.won})
	if _banked:
		Meta.update_records(run_state.to_result())
	else:
		Meta.absorb_run(run_state.to_result())
	Sfx.play(&"death")
	get_tree().paused = true
	game_over.show_results(time_survived, kills, level)
