extends SceneTree
## Authors every skill-tree node .tres plus its manifest.
##
##   <console.exe> --headless --path . -s res://tools/gen_skills.gd
##
## Same shape as tools/gen_upgrades.gd, and for the same reason: a hand-written
## content list drifts, and this project has already shipped a retired upgrade 62
## times because of one. The manifest is emitted from the ids actually saved, and
## orphaned .tres files are pruned.
##
## PRICING is in shards, which are earned at 6/minute plus 25 per boss event
## cleared (MetaState.shards_for). A first run that dies at 3:00 pays ~18; a
## 5-minute win pays ~55; a full 10-minute run clearing both events pays ~110. The
## cheap tier is therefore reachable after two or three real runs, and the
## Legendary card is a project.
##
## EVERYTHING HERE IS SMALL ON PURPOSE. Every difficulty number in the game is
## tuned against a zero-tree account, so the tree can only make the game easier
## than its target — that mitigation is the entire reason a permanent stat tree
## was acceptable to ship alongside a rebalance.

const OUT: String = "res://resources/skills"
const MANIFEST: String = "res://resources/skills/skill_list.gd"

var _written: Array[String] = []


func _init() -> void:
	var eff := UpgradeResource.Effect
	# id, name, description, cost, tier, effect, magnitude
	var stats: Array = [
		["node_hardy", "Hardened Frame", "+2 max HP, every run", 60, 0, eff.MAX_HP, 2.0],
		["node_magnet", "Field Coil", "+20px pickup range, every run", 45, 0, eff.MAGNET, 20.0],
		["node_swift", "Thruster Tune", "+6% move speed, every run", 70, 0, eff.MOVE_SPEED, 0.06],
		["node_keen", "Honed Emitter", "+1 damage, every run", 95, 1, eff.DAMAGE, 1.0],
		["node_quick", "Cycle Tuning", "6% faster firing, every run", 110, 1, eff.FIRE_RATE, 0.06],
		["node_scholar", "Data Siphon", "+8% XP gained, every run", 130, 1, eff.XP_GAIN, 0.08],
	]
	for d: Array in stats:
		var payload := UpgradeResource.new()
		payload.id = StringName(String(d[0]) + "_payload")
		payload.display_name = d[1]
		payload.description = d[2]
		payload.effect = d[5]
		payload.magnitude = d[6]
		payload.max_stacks = 1
		_write_node(d[0], d[1], d[2], d[3], d[4], SkillNode.Kind.STAT, payload, &"")

	# CARD nodes. These add a card to the DRAFT POOL — they grant nothing on their
	# own, so the strongest thing money can buy here is still a possibility. One
	# per tier above Common, because the catalogue's job is to show the player a
	# ladder they can see the top of.
	var cards: Array = [
		["node_card_coils", "Overload Coils", "Adds a Rare card: 35% faster firing", 160, 2, &"shop_coils"],
		["node_card_hollow", "Hollow Point", "Adds an Epic card: enemies below 22% HP die instantly", 220, 2, &"shop_hollow"],
		["node_card_mirror", "Mirror Shards", "Adds a Legendary card: shots split into five", 320, 3, &"shop_mirror"],
	]
	for d: Array in cards:
		_write_node(d[0], d[1], d[2], d[3], d[4], SkillNode.Kind.CARD, null, d[5])

	_write_manifest()
	_prune_orphans()
	print("gen_skills: %d nodes + manifest" % _written.size())
	quit(0)


func _write_node(id: String, display_name: String, description: String, cost: int,
		tier: int, kind: SkillNode.Kind, payload: UpgradeResource,
		grants_card: StringName) -> void:
	var node := SkillNode.new()
	node.id = StringName(id)
	node.display_name = display_name
	node.description = description
	node.cost = cost
	node.tier = tier
	node.kind = kind
	node.payload = payload
	node.grants_card = grants_card
	var path: String = "%s/%s.tres" % [OUT, id]
	node.resource_path = path
	if ResourceSaver.save(node, path) != OK:
		push_error("gen_skills: FAILED %s" % path)
		return
	_written.append(id)


## Explicit preloads rather than a DirAccess scan: directory listings misbehave
## inside an exported .pck (resources gain .remap suffixes), so the tree would
## silently empty itself on the web build only.
func _write_manifest() -> void:
	_written.sort()
	var lines: PackedStringArray = [
		"class_name SkillList",
		"## GENERATED by tools/gen_skills.gd — DO NOT HAND-EDIT.",
		"##",
		"## Regenerate:",
		"##   <console.exe> --headless --path . -s res://tools/gen_skills.gd",
		"",
		"const ALL: Array[SkillNode] = [",
	]
	for id: String in _written:
		lines.append("\tpreload(\"%s/%s.tres\")," % [OUT, id])
	lines.append("]")
	lines.append("")
	var file: FileAccess = FileAccess.open(MANIFEST, FileAccess.WRITE)
	if file == null:
		push_error("gen_skills: cannot write %s" % MANIFEST)
		return
	file.store_string("\n".join(lines))


func _prune_orphans() -> void:
	var dir: DirAccess = DirAccess.open(OUT)
	if dir == null:
		return
	for file_name: String in dir.get_files():
		if not file_name.ends_with(".tres"):
			continue
		if _written.has(file_name.get_basename()):
			continue
		if dir.remove(file_name) == OK:
			print("gen_skills: pruned orphan %s" % file_name)
